describe('Single credit tests', () =>{

    before('connection site test', () =>{
        cy.visit('https://www.younited-credit.com/')
        cy.url()
            .should('include', 'younited-credit')
        cy.get('title')
            .should('contain', 'Le Crédit 100% en Ligne – Réponse en 24h | Younited Credit')
    })

    it('landing page', () =>{
        cy.get('#projectSelect')
            .select('HITECH')
        cy.get('#amount')
            .select('2K')
        cy.get('#creditMaturity')
            .select('M12')
        cy.contains('CONTINUER')
            .click()
        cy.url()
            .should('include', '/email')
        cy.get('title')
            .should('contain','Younited Credit')
    })

    it('Email page', () =>{
        cy.get('#email-input').type('fosigaza-0467@yopmail.com')
            .should('have.value','fosigaza-0467@yopmail.com')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Voir mon offre personnalisée')
            .click()
        cy.url()
            .should('include', '/familysituation')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    
    it('Family situation page', () =>{
        cy.get('#maritalStatus-input')
            .select('COHABITING')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#childNumberPropal-input')
            .select('1')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('[type="checkbox"]')
            .check({force:true}) 
        cy.button_Suite()
        cy.url()
            .should('include', '/housing')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('House page', () =>{
        cy.get('#housingStatus-input')
            .select('LODGING_PROVIDED_BY_PARTNER')
        cy.get('#housingStatusFrom-input-month')
            .type('6')
        cy.get('#housingStatusFrom-input-year')
            .type('1980')
        cy.get('[type="checkbox"]').check({force:true}) 
        cy.button_Suite()
        cy.url()
            .should('include', '/professionalsituation')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Professional situation Test', () =>{
        cy.get('#activitySector-input')
            .select('RETIRED')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#profession-input')
            .select('RETIRED_FROM_PUBLIC_SECTOR')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.wait(2000)
        cy.get('#pensionFrom-input-month')
            .type('12')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.wait(2000)
        cy.get('#pensionFrom-input-year')
            .type('2015')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.button_Suite()
        cy.url().should('include', '/partnerprofession')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Partner Activity Sector Test', () =>{
        cy.get('#partnerActivitySector-input')
            .select('RETIRED')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#partnerProfession-input')
            .select('RETIRED_FROM_PRIVATE_SECTOR')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#partnerPensionFrom-input-month')
            .type('6')
        cy.get('#partnerPensionFrom-input-year')
            .type('2010')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.button_Suite()
        cy.url().should('include', '/incomes')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Main Income Test', () =>{
        cy.get('#mainIncome-input')
            .type('2000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#coIncome-input')
            .type('2500')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#housingAssistance-input')
            .type('0')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#additionalIncome-input')
            .type('1500')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/outcomes')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Rent Amount Test', () =>{
        cy.get('#rentAmount-input')
            .type('200')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#childSupportPaymentsAmount-input')
            .type('0')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#childCareExpensesAmount-input')
            .type('700')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#loanCount-input')
            .select('0')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/bank')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Bank Test', () =>{
        cy.get('#bankCode-input')
            .select('HSBC')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#bankFrom-input-year')
            .type('1980')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/identity')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Identity Test', () =>{
        cy.get('#GENDERCODE_M')
            .check({ force: true })
            .should('be.checked')
        cy.get('#lastName-input')
            .type('Posichon')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#firstName-input')
            .type('Paul')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#dateOfBirth-input-day')
            .type('2')
        cy.get('#dateOfBirth-input-month')
            .type('1')
        cy.get('#dateOfBirth-input-year')
            .type('1957')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#postalCode-input')
            .type('06000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#city-input')
            .select('608806000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/partneridentity')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Partner Identity Test', () =>{
        cy.get('#GENDERCODE_MLLE')
            .check({ force: true })
            .should('be.checked')
        cy.get('#lastName-input')
            .type('Brasletti')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#firstName-input')
            .type('Guina')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#dateOfBirth-input-day')
            .type('26')
        cy.get('#dateOfBirth-input-month')
            .type('9')
        cy.get('#dateOfBirth-input-year')
            .type('1960')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#postalCode-input')
            .type('92000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#city-input')
            .select('9205092000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/contact')
        cy.get('title')
            .should('contain','Younited Credit')
    })

    it('Identity Test', () =>{
        cy.get('#cellPhoneNumber-input')
            .type('07785541269')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#phoneNumber-input')
            .type('09687452120')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#address-input')
            .type('69 Bld Bracame')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#postalCode-input')
            .type('33000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#city-input')
            .select('3306333000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#countryZone-input')
            .select('FR')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/offers')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Assurance Test', () =>{
        cy.get('#insurance-subscribers-input')
            .select('YES_NO')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/verification')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Whithout Assurance Test', () =>{
        cy.contains('Continuer sans assurance')
            .click()
    })
    it('Commercial Offer Test', () =>{
        cy.url().should('include', '/modify-offer')
        cy.get('title')
            .should('contain','Younited Credit')
    })
})