describe('Single credit tests', () =>{

    before('connection site test', () =>{
        cy.visit('https://www.younited-credit.com/')
        cy.url()
            .should('include', 'younited-credit')
        cy.get('title')
            .should('contain', 'Le Crédit 100% en Ligne – Réponse en 24h | Younited Credit')
    })

    it('landing page', () =>{
        cy.get('#projectSelect')
            .select('NEWCAR')
        cy.get('#amount')
            .select('10K')
        cy.get('#creditMaturity')
            .select('M60')
        cy.contains('CONTINUER')
            .click()
        cy.url()
            .should('include', '/email')
        cy.get('title')
            .should('contain','Younited Credit')
    })

    it('Email page', () =>{
        cy.get('#email-input').type('fosigaza-0467@yopmail.com')
            .should('have.value','fosigaza-0467@yopmail.com')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Voir mon offre personnalisée')
            .click()
        cy.url()
            .should('include', '/familysituation')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    
    it('Family situation page', () =>{
        cy.get('#maritalStatus-input')
            .select('SINGLE')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#childNumberPropal-input')
            .select('0')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('[type="checkbox"]')
            .uncheck({force:true}) 
        cy.contains('Suite')
            .click()
        cy.url()
            .should('include', '/housing')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('House page', () =>{
        cy.get('#housingStatus-input')
            .select('TENANT')
        cy.get('#housingStatusFrom-input-month')
            .type('4')
        cy.get('#housingStatusFrom-input-year')
            .type('2015')
        cy.get('[type="checkbox"]').uncheck({force:true}) 
        cy.contains('Suite')
            .click()
        cy.url()
            .should('include', '/professionalsituation')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Professional situation Test', () =>{
        cy.get('#activitySector-input')
            .select('INDEPENDENT')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#profession-input')
            .select('CRAFTSMAN')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#businessActivityStartDate-input-month')
            .type('4')
        cy.get('#businessActivityStartDate-input-year')
            .type('2000')
        cy.get('#ISCOMPANYBANKRUPT_FALSE')
            .check({ force: true })
            .should('be.checked')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/incomes')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Main Income Test', () =>{
        cy.get('#mainIncome-input')
            .type('2000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#housingAssistance-input')
            .type('300')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#additionalIncome-input')
            .type('0')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/outcomes')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Rent Amount Test', () =>{
        cy.get('#rentAmount-input')
            .type('900')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#loanCount-input')
            .select('1')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#type-input')
            .select('REFURBISHMENT_WORKS')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#loanAmount-input')
            .type('500')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/bank')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Bank Test', () =>{
        cy.get('#bankCode-input')
            .select('SOCIETE_GENERALE')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#bankFrom-input-year')
            .type('1998')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/identity')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Identity Test', () =>{
        cy.get('#GENDERCODE_M')
            .check({ force: true })
            .should('be.checked')
        cy.get('#lastName-input')
            .type('DuCable')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#firstName-input')
            .type('Jean-Raoul')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#dateOfBirth-input-day')
            .type('20')
        cy.get('#dateOfBirth-input-month')
            .type('2')
        cy.get('#dateOfBirth-input-year')
            .type('1970')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#postalCode-input')
            .type('33000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#city-input')
            .select('3306333000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/contact')
        cy.get('title')
            .should('contain','Younited Credit')
    })

    it('Identity Test', () =>{
        cy.get('#cellPhoneNumber-input')
            .type('0645879936')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#phoneNumber-input')
            .type('0598553214')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#address-input')
            .type('54 Rue Vilbrequin')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#postalCode-input')
            .type('33000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#city-input')
            .select('3306333000')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.get('#countryZone-input')
            .select('FR')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
        cy.url().should('include', '/offers')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    it('Assurance Test', () =>{
        cy.get('#insurance-subscribers-input')
            .select('YES')
        cy.get('div').should('have.class', 'wrapper-input input-wrapper--valid')
        cy.contains('Suite')
            .click()
    })
    it('Commercial Offer Test', () =>{
        cy.url().should('include', '/modify-offer')
        cy.get('title')
            .should('contain','Younited Credit')
    })
    
    


})